version: '3.9'
services:
  db:
    image: postgres:15.6
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    env_file:
      - postgres.env
    volumes:
      - ./postgres-mount:/var/lib/postgresql/data
    stdin_open: true
    ports:
      - "5433:5432"
