// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
use chrono::DateTime;
use chrono::offset::Utc;
#[derive(Queryable, Debug, Identifiable)]
pub struct Activity {
    pub id: i64,
    pub user_id: i64,
    pub task_id: i64,
    pub title: String,
    pub description: Option<String>,
    pub status: /* TODO: unknown type StatusEnum */,
    pub created_at: NaiveDateTime,
    pub updated_at: Option<NaiveDateTime>,
    pub planned_start_date: Option<NaiveDateTime>,
    pub planned_end_date: Option<NaiveDateTime>,
    pub actual_start_date: Option<NaiveDateTime>,
    pub actual_end_date: Option<NaiveDateTime>,
    pub content: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Comment {
    pub id: i64,
    pub task_id: i64,
    pub activity_id: Option<i64>,
    pub title: String,
    pub created_at: NaiveDateTime,
    pub updated_at: Option<NaiveDateTime>,
    pub content: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Tag {
    pub id: i64,
    pub title: String,
    pub slug: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(task_id, tag_id))]
pub struct TaskTag {
    pub task_id: i64,
    pub tag_id: i64,
}

#[derive(Queryable, Debug)]
pub struct Task {
    pub id: i64,
    pub user_id: i64,
    pub created_by: i64,
    pub updated_by: i64,
    pub title: String,
    pub description: Option<String>,
    pub status: /* TODO: unknown type StatusEnum */,
    pub created_at: NaiveDateTime,
    pub updated_at: Option<NaiveDateTime>,
    pub planned_start_date: Option<NaiveDateTime>,
    pub planned_end_date: Option<NaiveDateTime>,
    pub actual_start_date: Option<NaiveDateTime>,
    pub actual_end_date: Option<NaiveDateTime>,
    pub content: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i64,
    pub is_admin: bool,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub username: String,
    pub mobile: Option<String>,
    pub email: Option<String>,
    pub password_hash: String,
    pub registered_at: DateTime<Utc>,
    pub last_login: Option<NaiveDateTime>,
    pub intro: Option<String>,
}

